### ISSUE TITLE
Function istext sometimes gives wrong results

### ISSUE THREAD

**Issue by exilef** [PythonCharmers/python-future#154]
In a specific setup (did not have time to investigate the root cause or come up with a minimal example, in my specific case it happens in the json module that tries to sort keys) I end up with a list of objects (all strings), but of different types that the istext function wrongly reports to be not of text type.

It raises the following exceptions in the compare methods (`__lt__`, ...) because `istext` returns `False`:

`exceptions.TypeError: ("unorderable types: str() and <type 'str'>",)`

This can be fixed by changing the check in the (deprecated) method `istext` in `utils/__init__.py` to

`return isinstance(obj, type(u'')) or isinstance(obj, str)`

**Comment by azmeuk** [comment]
I could reproduce this bug with:
``` python
>>> from builtins import str
>>> "" < str("")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../env/lib/python2.7/site-packages/future/types/newstr.py", line 316, in __gt__
    raise TypeError(self.unorderable_err.format(type(other)))
TypeError: unorderable types: str() and <type 'str'>
```
