### ISSUE TITLE
Python 2.6: TypeError: create_connection() takes at most 2 arguments (3 given)

### ISSUE THREAD

**Issue by QuLogic** [PythonCharmers/python-future#162]
We're seeing [this traceback](https://travis-ci.org/obspy/obspy/jobs/73583936#L375) on Python 2.6:
```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/obspy/core/tests/test_stream.py", line 1687, in test_read
    tr = read('http://examples.obspy.org/test.sac', dtype=np.int32)[0]
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/obspy/core/util/decorator.py", line 307, in new_func
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/obspy/core/stream.py", line 225, in read
    fh.write(urllib.request.urlopen(pathname_or_url).read())
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/urllib/request.py", line 171, in urlopen
    return opener.open(url, data, timeout)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/urllib/request.py", line 494, in open
    response = self._open(req, data)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/urllib/request.py", line 512, in _open
    '_open', req)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/urllib/request.py", line 466, in _call_chain
    result = func(*args)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/urllib/request.py", line 1311, in http_open
    return self.do_open(http_client.HTTPConnection, req)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/urllib/request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/http/client.py", line 1092, in request
    self._send_request(method, url, body, headers)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/http/client.py", line 1130, in _send_request
    self.endheaders(body)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/http/client.py", line 1088, in endheaders
    self._send_output(message_body)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/http/client.py", line 933, in _send_output
    self.send(msg)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/http/client.py", line 869, in send
    self.connect()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/future/backports/http/client.py", line 847, in connect
    self.timeout, self.source_address)
TypeError: create_connection() takes at most 2 arguments (3 given)
```

**Comment by QuLogic** [comment]
Ping? This is really annoying in Travis builds.

**Comment by edschofield** [comment]
Oops, I missed this bug report before. I'll take a look at it ASAP.

**Comment by megies** [comment]
Ping? This is completely messing up our Travis results. I'm already considering to have our project depend on `future<0.15`.

**Comment by edschofield** [comment]
I've released a new version (v0.15.1) that should fix this. Could you please test it and let me know if your ``urllib.request.urlopen()`` tests pass on Py2.6 now?

**Comment by QuLogic** [comment]
The error has [moved elsewhere](https://travis-ci.org/obspy/obspy/jobs/79299423).

**Comment by edschofield** [comment]
Thanks for letting me know. This doesn't seem to be covered by ``future``'s test suite on Py2.6 ...

**Comment by edschofield** [comment]
I've added new tests and fixed it (I hope) in v0.15.2.

**Comment by megies** [comment]
Rerun one of the above [Travis builds](https://travis-ci.org/obspy/obspy/jobs/74431903), can confirm it works.

**Comment by edschofield** [comment]
Great, thanks!

**Comment by megies** [comment]
Thanks for fixing it!
