### ISSUE TITLE
configparser in site-packages breaks making a virtualenv with python3

### ISSUE THREAD

**Issue by michaelpacer** [PythonCharmers/python-future#181]
Installing future using (`pip install future`) breaks the ability to make virtualenvironments with python3 using the standard 

    virtualenv -p $(which python3) py3

command. 

It returns the following error
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 42, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 44, in <module>
    import configparser as ConfigParser
  File "/usr/local/lib/python2.7/site-packages/configparser/__init__.py", line 11, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

This seems like this is a related but separate issue from https://github.com/PythonCharmers/python-future/issues/118. Nonetheless, more generally I really agree with @Julian

> More generally, python-future should not install modules that shadow other installed modules IMO. Most of the other ones are less likely to be issues, so it might be preferable to just do that rather than adding a faux dependency.

from https://github.com/PythonCharmers/python-future/issues/118#issuecomment-68616949

It took a really long time to trace the source of this since there's no way to obviously recognize that the `configparser.py` installed to `site-packages` is not the standard `configparser` package and that its simply being there *was* the problem. 

This also may be related to the OP http://serverfault.com/a/734568/317373 which does date from after the https://github.com/PythonCharmers/python-future/issues/118 issue, but before I ran into this problem, so I'm not sure if it's actually related.

**Comment by Julian** [comment]
FWIW IMO, this is not python-future's issue to fix. It's virtualenv that's terrible. virtualenv is undergoing a rewrite to fix some of its issues, but the fact that having python-future installed to 2.7 breaks python 3 virtualenvs is because virtualenv is crazy and exec's the target Python interpreter possibly after some modules have been installed.

The PyPA team (or at least @dstufft) generally recommends that you avoid `-p ` and install virtualenv to each Python you want to use it from, and then use `targetpython -m virtualenv`. Or alternatively to run virtualenv.py from them. Or alternatively alternatively :), I wrote mkenv which solves this indirectly.

**Comment by QuLogic** [comment]
Since #118 is fixed now, maybe this can be closed?
