### ISSUE TITLE
Running `tox` fails on project converted with `futurize`

### ISSUE THREAD

**Issue by Daenyth** [PythonCharmers/python-future#191]
I'm trying to update this to work for python2 and python3: https://github.com/CurataEng/salesforce-python-toolkit/tree/python3

I ran `futurize` on the source and tests, and adding it to setup.py

If I run `tox`, I get this: 

```
ERROR: InvocationError: '/Users/daenyth/Curata/salesforce-python-toolkit/.tox/py27/bin/nosetests'
py35 create: /Users/daenyth/Curata/salesforce-python-toolkit/.tox/py35
ERROR: invocation failed (exit code 1), logfile: /Users/daenyth/Curata/salesforce-python-toolkit/.tox/py35/log/py35-0.log
ERROR: actionid: py35
msg: getenv
cmdargs: ['/usr/local/opt/python/bin/python2.7', '-m', 'virtualenv', '--python', '/usr/local/bin/python3.5', 'py35']
env: {'LOGNAME': 'daenyth', 'USER': 'daenyth', 'HOME': '/Users/daenyth', 'PATH': '/Users/daenyth/Curata/salesforce-python-toolkit/.tox/py35/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/daenyth/.stack/programs/x86_64-osx/ghc-7.10.2/bin:/Users/daenyth/.stack/snapshots/x86_64-osx/lts-3.16/7.10.2/bin', 'VIRTUALENVWRAPPER_SCRIPT': '/usr/local/bin/virtualenvwrapper.sh', 'TERM_PROGRAM': 'iTerm.app', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'COLORFGBG': '7;0', 'SHLVL': '1', 'SECURITYSESSIONID': '186a5', 'XPC_FLAGS': '0x0', 'ITERM_SESSION_ID': 'w1t1p0', 'PYTHONHASHSEED': '4165956177', '_': '/usr/local/bin/tox', 'WORKON_HOME': '/Users/daenyth/Curata/.env', 'XPC_SERVICE_NAME': '0', 'COMP_WORDBREAKS': ' \t\n"\'><;|&(:', 'VIRTUAL_ENV': '/Users/daenyth/Curata/salesforce-python-toolkit/.tox/py35', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.3Y17OJGMF5/Listeners', 'Apple_PubSub_Socket_Render': '/private/tmp/com.apple.launchd.viGM1pyBDG/Render', 'ITERM_PROFILE': 'Default', 'TMPDIR': '/var/folders/88/f3twmqg95t95_03rxspf2ptr0000gn/T/', 'VIRTUALENVWRAPPER_PROJECT_FILENAME': '.project', 'VIRTUALENVWRAPPER_HOOK_DIR': '/Users/daenyth/Curata/.env', 'OLDPWD': '/Users/daenyth', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'PWD': '/Users/daenyth/Curata/salesforce-python-toolkit', 'VIRTUALENVWRAPPER_WORKON_CD': '1', 'COMMAND_MODE': 'unix2003'}

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/virtualenv.py", line 14, in <module>
    import shutil
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/shutil.py", line 10, in <module>
    import fnmatch
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/fnmatch.py", line 15, in <module>
    import functools
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/collections/__init__.py", line 16, in <module>
    from reprlib import recursive_repr as _recursive_repr
  File "/usr/local/lib/python2.7/site-packages/reprlib/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
Running virtualenv with interpreter /usr/local/bin/python3.5

ERROR: InvocationError: /usr/local/opt/python/bin/python2.7 -m virtualenv --python /usr/local/bin/python3.5 py35 (see /Users/daenyth/Curata/salesforce-python-toolkit/.tox/py35/log/py35-0.log)
_________________________________________________________________________________________________ summary __________________________________________________________________________________________________
ERROR:   py27: commands failed
ERROR:   py35: InvocationError: /usr/local/opt/python/bin/python2.7 -m virtualenv --python /usr/local/bin/python3.5 py35 (see /Users/daenyth/Curata/salesforce-python-toolkit/.tox/py35/log/py35-0.log)
```

This seems to be related to #148, but as a regular user I'm not sure of the best way to proceed for the moment. How can I best resolve this?

**Comment by Daenyth** [comment]
ping @edschofield (it seems like you're the most active developer at the moment)

**Comment by justinabrahms** [comment]
Wanted to comment that this is breaking for my project as well (when pulling in https://github.com/twidi/django-decorator-include)

**Comment by Daenyth** [comment]
@justinabrahms I was able to get around it by calling tox from a python3 virtualenv - try that?

**Comment by justinabrahms** [comment]
Given my current build setup with docker, that's going to be a pain, not to
mention that having tox should mean I don't have to do all of this
virtualenv management. :(

Thanks for the suggestion. I'll probably try it later this week.

**Comment by jmadler** [comment]
Closing as this conversation has stalled and there appears to be no remaining action for `python-future`.  Please reopen if I may be mistaken :)
