### ISSUE TITLE
Importing imp in standard_library raises a PendingDeprecationWarning

### ISSUE THREAD

**Issue by jfinkels** [PythonCharmers/python-future#246]
The `imp` package is pending deprecation in favor of `importlib` as of Python 3.4.
```sh
$ python3.5 -Wonce -c "import future.standard_library"
[...]/lib/python3.5/site.py:165: DeprecationWarning: 'U' mode is deprecated
  f = open(fullname, "rU")
[...]/lib/python3.5/site-packages/future/standard_library/__init__.py:66: PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```
The recommended alternative is described [here][1].

[1]: https://docs.python.org/3.6/library/imp.html#imp.find_module

**Comment by gGonz** [comment]
Any hope to get this fixed? Still happening after 3 years.

**Comment by elderlabs** [comment]
Assuming no one has plans to fix this? Currently tracking the source of a `DeprecationWarning` and found this along the way.

**Comment by elderlabs** [comment]
Greetings again from the `future`. We're now in the days of Python 3.11, with Python 3.12's release looming ever closer. There is an open PR (#574) from 2019 to close this issue.

Is python-future dead? Once Python 3.12 releases, this project will be left in a forever broken state if not updated. 
Please merge the pending PR.

**Comment by hugovk** [comment]
The `imp` module has now been removed from Python 3.12.

* https://github.com/python/cpython/issues/98040
* https://github.com/python/cpython/pull/98573

Python 3.12 will be in [beta in two weeks](https://peps.python.org/pep-0693/), and [set for release on 2023-10-02](https://devguide.python.org/versions/) and this library is one of the [top 5,000 most-downloaded from PyPI](https://hugovk.github.io/top-pypi-packages/).

Please could you upgrade to use `importlib`? The [`imp` docs](https://docs.python.org/3.11/library/imp.html) have suggestions on what to use to replace each function and constant.

**Comment by yonran** [comment]
For people googling, in python 3.12, importing `future.standard_library` raises “ModuleNotFoundError: No module named 'imp'”:

```
ImportError: Failed to import test module: myfile
Traceback (most recent call last):
  …
  File "myfile.py", line 41, in <module>
    from future import standard_library
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

In my case, I resolved the error by replacing those imports that need `future.standard_library.install_aliases()` with [six](https://six.readthedocs.io/#module-six.moves) instead (see [imports2](https://github.com/PythonCharmers/python-future/blob/v0.18.3/src/libpasteurize/fixes/fix_imports2.py#L85-L101)):

* `urllib.parse` --> `six.moves.urllib.parse`
* `urllib.error` --> `six.moves.urllib.error`
* `urllib.parse` -->`six.moves.urllib.parse` 
* `dbm.ndbm` --> `six.moves. dbm_ndbm`
* `http.server` --> `six.BaseHTTPServer`, `six.CGIHTTPServer`, or `six.SimpleHTTPServer`
* `tkinter.filedialog` --> `six.tkinter_tkfiledialog`
* `tkinter.simpledialog` --> `six.tkinter_simpledialog`
* `xmlrpc.server` --> `six.xmlrpc_server`
