### ISSUE TITLE
Py2/3 support for Python 3 code using FileExistsError

### ISSUE THREAD

**Issue by dspruell** [PythonCharmers/python-future#251]
I have code tested in Python 3 (3.5.2) that uses `FileExistsError` and have used `pasteurize` to attempt Py2/3 support. When I attempt to run the code under a Python 2.6.6 environment (installed importlib, unittest2, argparse beforehand), it encounters a NameError because of undefined `FileExistsError`:

```
Traceback (most recent call last):
  File "/home/dspruell/devel/project/env/bin/project-cmd", line 11, in <module>
    load_entry_point('project==0.2.4', 'console_scripts', 'project-cmd')()
  File "/home/dspruell/devel/project/env/lib/python2.6/site-packages/project/cli.py", line 86, in main
    except FileExistsError as e:
NameError: global name 'FileExistsError' is not defined
```

Following are the use in modules:

```
try:
        args.func(args)
    except FileExistsError as e:
        parser.error('Refusing to clobber existing path ({err})'.format(err=e))
```

```
try:
        os.makedirs(configdir)
    except FileExistsError as e:
        if not args.force:
            raise
```

For what it's worth, under Python 2.6 the exception that's raised in place of FileExistsError is OSError.

Is this something one should expect python-future to handle?

**Comment by edschofield** [comment]
Thanks for asking, @dspruell. I have committed a patch to a new development branch called `exceptions`. You can use the new PEP3151 exceptions with code like this:
```
from builtins import FileNotFoundError
```
at the top of modules that invoke those exceptions.

Could you please try the new branch and report back about how well this works for you?

**Comment by edschofield** [comment]
See also issue #254

**Comment by alexamici** [comment]
@jmadler adding new Python3 exceptions to Python2 looks like a low hanging fruit that would make a lot of code much nicer.

This is the [new Exception hierarchy](https://docs.python.org/3/library/exceptions.html#os-exceptions) compared to the [old Exception hierarchy](https://docs.python.org/2/library/exceptions.html#exception-hierarchy).
