### ISSUE TITLE
future.backports.urllib.parse.urlunsplit breaks with mixed `unicode` and `str` inputs

### ISSUE THREAD

**Issue by rclmenezes** [PythonCharmers/python-future#273]
In Python 2's `urlparse.urlunsplit`, you can mix unicode and str:

```python
> from urlparse import urlunsplit
> urlunsplit((u'scheme', 'netloc', 'url', 'query', 'fragment'))
u'scheme://netloc/url?query#fragment'
```

However, future.backports.urllib.parse.urlunsplit breaks with this input:

``` python
> from future.backports.urllib.parse import urlunsplit
> urlunsplit((u'scheme', 'netloc', 'url', 'query', 'fragment'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/parse.py", line 399, in urlunsplit
    _coerce_args(*components))
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/parse.py", line 115, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

This causes `standard_library.install_aliases()` to break several popular libraries that use urllib.parse.urlunsplit, like [kombu](https://github.com/celery/kombu/).

It seems that the problem is the [`_coerce_args` function](https://github.com/PythonCharmers/python-future/blob/master/src/future/backports/urllib/parse.py#L104):
```python
def _coerce_args(*args):
    # Invokes decode if necessary to create str args
    # and returns the coerced inputs along with
    # an appropriate result coercion function
    #   - noop for str inputs
    #   - encoding function otherwise
    str_input = isinstance(args[0], str)
    for arg in args[1:]:
        # We special-case the empty string to support the
        # "scheme=''" default argument to some functions
        if arg and isinstance(arg, str) != str_input:
            raise TypeError("Cannot mix str and non-str arguments")
    if str_input:
        return args + (_noop,)
    return _decode_args(args) + (_encode_result,)
```

I'm new to making Python3 compatible code. Can we simply replace `isinstance(args[0], str)` withh `isinstance(args[0], str) or isinstance(args[0], unicode)`? That worked for me when I monkey-patched `_coerce_args`. I can make a PR if you want.

Thanks!

**Comment by gatesn** [comment]
I think the solution ought to be one of these: http://python-future.org/compatible_idioms.html#basestring

**Comment by bendikro** [comment]
Got the same problem with `urlunparse` where the [dxf library](https://github.com/davedoesdev/dxf/blob/master/dxf/__init__.py#L11) imports 
 from `future.backports.urllib` instead of the python2 `urlparse` causing the same error.

How to solve this issue?

**Comment by sharkjacobs** [comment]
I edited lines 110 and 114 of future/backports/urllib/parse.py and changed "str" to "basestring" eg. isinstance(args[0], basestring)

I hope a proper tested fix comes soon but this worked for my use.

**Comment by gdbing** [comment]
I edited lines 110 and 114 of future/backports/urllib/parse.py and changed "str" to "basestring" eg. isinstance(args[0], basestring)

I hope a proper tested fix comes soon but this worked for my use.

**Comment by jmadler** [comment]
future.backports.* is supposed to backport breaking behavior, not forward port permissive behavior. 
 Py2's implementation doesn't raise for mixed types, but Py3's does.  

As such, I think we should probably consider this bug "wontfix" and revert the PR.

Are there any concerns with that approach?

**Comment by Kfir-Nissim** [comment]
I'm afraid that this causes a conflict between 2 packages we relay on in our project.
one dependency uses `future.standard_library.install_aliases()` while the other have this following code:
```python
try:
    # Python 3.
    from urllib.parse import parse_qs
except ImportError:
    # Python 2.5+
    from urlparse import urlparse
    try:
        # Python 2.6+
        from urlparse import parse_qs
    except ImportError:
        # Python <=2.5
        from cgi import parse_qs
```
The issue is that the second package does not use unicode objects, and expects `parse_qs` to work with `str`
