### ISSUE TITLE
str.split not working

### ISSUE THREAD

**Issue by elehcim** [PythonCharmers/python-future#284]
Is this a bug or I am missing something?
```
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2

>>> from __future__ import unicode_literals
>>> from builtins import str
>>> str.split("poi_324", "_")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/lib/python2.7/site-packages/future/types/__init__.py", line 165, in wrapper
    return function(*args, **kwargs)
  File "/home/user/anaconda3/lib/python2.7/site-packages/future/types/newstr.py", line 244, in split
    parts = super(newstr, self).split(sep, maxsplit)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

I am using future 0.16

**Comment by elehcim** [comment]
Using split with the syntax:

    "poi_324".split("_")

it works.
