### ISSUE TITLE
future.moves.urllib.request broken with Python 3.8

### ISSUE THREAD

**Issue by yan12125** [PythonCharmers/python-future#350]
The CPython pull requests https://github.com/python/cpython/pull/2205 removes splitattr and other undocumented functions from urllib.request, leading to the failure in future.moves.urllib.request:

```
$ python3.8 -c 'from future.moves.urllib import request as urllib_request'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yen/.local/lib/python3.8/site-packages/future/moves/urllib/request.py", line 9, in <module>
    from urllib.request import (getproxies,
ImportError: cannot import name 'splitattr' from 'urllib.request' (/usr/lib/python3.8/urllib/request.py)
```

Python version: python/cpython@612dbefe9d
future version: git master

**Comment by yan12125** [comment]
Closing for the same reason as  #382.
