### ISSUE TITLE
future's range does not seem to be as compatible as six' range

### ISSUE THREAD

**Issue by fersarr** [PythonCharmers/python-future#408]
future's range does not seem to be as compatible as six' range:

```
>>> from builtins import range as future_range
>>> from six.moves import range as six_range   
>>> not 'C' in six_range(2)
True
>>> not 'C' in xrange(2)
True
>>> not 'C' in future_range(2)
Traceback (most recent call last):
  File "<pudb command line>", line 1, in <module>
  File "/xxx/future-0.16.0-py2.7.egg/future/types/newrange.py", line 109, in __contains__
    self.index(value)
  File "/xxx/future-0.16.0-py2.7.egg/future/types/newrange.py", line 93, in index
    diff = value - self._start
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by ghanshyam-lele** [comment]
looks like this is already solved 

`    def __contains__(self, value):
        """Return ``True`` if the integer `value` occurs in
        the sequence this range represents."""
        try:
            self.index(value)
            return True
        except ValueError:
            return False`
