### ISSUE TITLE
pip install broken on 0.17.1

### ISSUE THREAD

**Issue by dantonpimentel** [PythonCharmers/python-future#410]
Hello,

I've been getting this error since  the upgrade to 0.17.1 was released.

```
# pip install --upgrade future
Collecting future
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-JWMEZH/future/setup.py", line 181, in <module>
        **setup_kwds
      File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib64/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 302, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2343, in load
        return self.resolve()
      File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2353, in resolve
        raise ImportError(str(exc))
    ImportError: 'module' object has no attribute 'check_specifier'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-JWMEZH/future/

```

The server has the latest pip installed
```
# pip --version
pip 18.1 from /usr/lib/python2.7/site-packages/pip (python 2.7)

```

I wonder if anyone else is having this issue.

**Comment by dantonpimentel** [comment]
I reinstalled setuptools on my server and everything seems to be fine now. Weird error.
