### ISSUE TITLE
__bool__ = __nonzero__ not detected

### ISSUE THREAD

**Issue by spaceone** [PythonCharmers/python-future#453]
Code like:
```
class Foo(object):
    def __nonzero__(self):
        return True
    __bool__ = __nonzero__
```

results in
```
from builtins import object
class Foo(object):
    def __bool__(self):
        return True
    __bool__ = __nonzero__
```

and therefore raises in Python3:
```Traceback (most recent call last):
  File "test.py", line 2, in <module>
    class Foo(object):
  File "test.py", line 5, in Foo
    __bool__ = __nonzero__
NameError: name '__nonzero__' is not defined


```

**Comment by molzami** [comment]
Looking at the code, shouldn't that line be 
__nonzero__ = __bool__ 

??

**Comment by spaceone** [comment]
Yes, that should be the resulting line.
