### ISSUE TITLE
`ImportError: cannot import name MaxRetryError` when trying to 

### ISSUE THREAD

**Issue by ngie-eign** [PythonCharmers/python-future#504]
I tried calling `standard_library.instal_aliases()` on my Fedora 30 host and it is resulting in an `ImportError`:
```
$ cat /etc/redhat-release 
Fedora release 30 (Thirty)
$ python2
Python 2.7.16 (default, Apr 30 2019, 15:54:43) 
[GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from future import standard_library
>>> standard_library.install_aliases()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/future/standard_library/__init__.py", line 466, in install_aliases
    import urllib
  File "urllib.py", line 3, in <module>
    from urllib.error import MaxRetryError
ImportError: cannot import name MaxRetryError
$ python
Python 2.7.16 (default, Apr 30 2019, 15:54:43) 
[GCC 9.0.1 20190312 (Red Hat 9.0.1-0.10)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.error import MaxRetryError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "urllib.py", line 3, in <module>
    from urllib.error import MaxRetryError
ImportError: cannot import name MaxRetryError
>>> 
[ecooper@wkstn-ecooper onefs]$ python3
Python 3.7.4 (default, Jul  9 2019, 16:32:37) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.error import MaxRetryError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ecooper/git/int/onefs/urllib.py", line 3, in <module>
    from urllib.error import MaxRetryError
ModuleNotFoundError: No module named 'urllib.error'; 'urllib' is not a package
>>> 
```
This exception only appears to be implemented in [urllib3](https://urllib3.readthedocs.io/en/latest/reference/#urllib3.exceptions.MaxRetryError).

**Comment by ngie-eign** [comment]
Just tried with the latest version:
```
$ python2 -c 'from future import standard_library; standard_library.install_aliases()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ecooper/.local/lib/python2.7/site-packages/future/standard_library/__init__.py", line 466, in install_aliases
    import urllib
  File "urllib.py", line 3, in <module>
    from urllib.error import MaxRetryError
ImportError: cannot import name MaxRetryError
```

**Comment by jmadler** [comment]
Can you submit a bugfix please? I'll include it in a release in the next few days.
