### ISSUE TITLE
Using build_opener with cookiejar thows AttributeError: 'HTTPMessage' object has no attribute 'getheaders'

### ISSUE THREAD

**Issue by bonham** [PythonCharmers/python-future#546]
- Create a cookiejar
- Create a build opener with HTTPCookieProcessor
- Open a URL 
This will throw:
`AttributeError: 'HTTPMessage' object has no attribute 'getheaders'
`
Run this example with future 0.18.2 and python 2.7.16 to reproduce

```
#!/usr/bin/env python

from future import standard_library
standard_library.install_aliases()
import urllib.request
import http.cookiejar


def main():

    cj = http.cookiejar.CookieJar()
    opener = urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cj))

    url = "https://www.google.com"
    opener.open(url)


main()

```
Stack Trace:

```
Traceback (most recent call last):
  File "cookie.py", line 18, in <module>
    main()
  File "cookie.py", line 15, in main
    opener.open(url)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 506, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/dist-packages/future/backports/urllib/request.py", line 1350, in http_response
    self.cookiejar.extract_cookies(response, request)
  File "/usr/lib/python2.7/cookielib.py", line 1667, in extract_cookies
    for cookie in self.make_cookies(response, request):
  File "/usr/lib/python2.7/cookielib.py", line 1584, in make_cookies
    rfc2965_hdrs = headers.getheaders("Set-Cookie2")
AttributeError: 'HTTPMessage' object has no attribute 'getheaders'

```
Tested on debian 10.2 in docker

**Comment by bhenry** [comment]
did you find a workaround? yes i see this is old. if i should be somewhere else, then set me in the right direction.
