### ISSUE TITLE
Email with base64-encoded UTF8 header Python2 bug

### ISSUE THREAD

**Issue by awdeorio** [PythonCharmers/python-future#555]
A bug in `future.backports.email.base64mime.header_encode` raises an exception when serializing an email message object containing a base64-encoded UTF8 header.

I have observed this problem on Python 2 only, with `future` library versions 0.17.1 and 0.18.2.
 
```python-repl
>>> import future.backports.email as email
>>> message = email.message_from_string(u"TO: Laȝamon <to@test.com>")
>>> message.as_string()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/message.py", line 155, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/generator.py", line 118, in flatten
    self._write(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/generator.py", line 190, in _write
    self._write_headers(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/generator.py", line 217, in _write_headers
    self.write(self.policy.fold(h, v))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/_policybase.py", line 321, in fold
    return self._fold(name, value, sanitize=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/_policybase.py", line 360, in _fold
    maxlinelen=self.max_line_length))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/header.py", line 375, in encode
    formatter.feed('', lines[0], charset)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/header.py", line 462, in feed
    encoded_lines = charset.header_encode_lines(string, self._maxlengths())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/charset.py", line 362, in header_encode_lines
    lines.append(encoder(header_bytes))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/backports/email/base64mime.py", line 73, in header_encode
    header_bytes = header_bytes.encode(charset)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/future/types/newbytes.py", line 406, in __getattribute__
    raise AttributeError("encode method has been disabled in newbytes")
AttributeError: encode method has been disabled in newbytes
```

Here's a suggested fix `future.backports.email.base64mime.header_encode`.  One line is changed, marked `New`.
```python
def header_encode(header_bytes, charset='iso-8859-1'):
    """Encode a single header line with Base64 encoding in a given charset.

    charset names the character set to use to encode the header.  It defaults
    to iso-8859-1.  Base64 encoding is defined in RFC 2045.
    """
    if not header_bytes:
        return ""
    if isinstance(header_bytes, str):
        # header_bytes = header_bytes.encode(charset)  # Old
        header_bytes = bytes(header_bytes, charset)    # New
    encoded = b64encode(header_bytes).decode("ascii")
    return '=?%s?b?%s?=' % (charset, encoded)
```

When I monkey patch the library with the suggested fix, it works.
```python-repl
>>> import future.backports.email as email
>>> from base64 import b64encode
>>> from future.builtins import bytes
>>> def header_encode(header_bytes, charset='iso-8859-1'):
...     """Encode a single header line with Base64 encoding in a given charset.
... 
...     charset names the character set to use to encode the header.  It defaults
...     to iso-8859-1.  Base64 encoding is defined in RFC 2045.
...     """
...     if not header_bytes:
...         return ""
...     if isinstance(header_bytes, str):
...         # header_bytes = header_bytes.encode(charset)  # Old
...         header_bytes = bytes(header_bytes, charset)    # New
...     encoded = b64encode(header_bytes).decode("ascii")
...     return '=?%s?b?%s?=' % (charset, encoded)
... 
>>> email.base64mime.header_encode = header_encode
>>> message = email.message_from_string(u"TO: Laȝamon <to@test.com>")
>>> message.as_string()
u'TO: =?utf-8?b?TGHInWFtb24gPHRvQHRlc3QuY29tPg==?=\n\n'
```

**Comment by awdeorio** [comment]
While I was working on fixing this, I found that it was already fixed in #534 .
