### ISSUE TITLE
Cannot install 0.18.2 on MacOS 10.15.2

### ISSUE THREAD

**Issue by kjagiello** [PythonCharmers/python-future#577]
Install fine when using the official python:3.9 docker image, but when installing locally on my mac, I get this error:

```python
$ python -V
Python 3.9.0
$ pip install future==0.18.2
Collecting future==0.18.2
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 6.5 MB/s
    ERROR: Command errored out with exit status 1:
     command: /tmp/xxx/.venv/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v9/kpfp8zmx1cq6pyqd9j3z_k9h0000gn/T/pip-install-dxpop5re/future/setup.py'"'"'; __file__='"'"'/private/var/folders/v9/kpfp8zmx1cq6pyqd9j3z_k9h0000gn/T/pip-install-dxpop5re/future/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/v9/kpfp8zmx1cq6pyqd9j3z_k9h0000gn/T/pip-pip-egg-info-ogmm5i9r
         cwd: /private/var/folders/v9/kpfp8zmx1cq6pyqd9j3z_k9h0000gn/T/pip-install-dxpop5re/future/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/xxx/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 3, in <module>
        from fnmatch import fnmatchcase
      File "/tmp/xxx/.venv/lib/python3.9/fnmatch.py", line 14, in <module>
        import re
      File "/tmp/xxx/.venv/lib/python3.9/re.py", line 127, in <module>
        import functools
      File "/tmp/xxx/.venv/lib/python3.9/functools.py", line 18, in <module>
        from collections import namedtuple
      File "/tmp/xxx/.venv/lib/python3.9/collections/__init__.py", line 39, in <module>
        from reprlib import recursive_repr as _recursive_repr
      File "/private/var/folders/v9/kpfp8zmx1cq6pyqd9j3z_k9h0000gn/T/pip-install-dxpop5re/future/src/reprlib/__init__.py", line 7, in <module>
        raise ImportError('This package should not be accessible on Python 3. '
    ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by kjagiello** [comment]
I realised that the issue was my PYTHONPATH being invalid. Closing this.
