### ISSUE TITLE
(past.builtins) ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [PythonCharmers/python-future#617]
It looks like `future-0.16.0` is not compatible with Python 3.10...

```
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import future, past  # No problem here...
>>> from past.builtins import basestring  # Here's the rub
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\EdingtonJames\AppData\Roaming\Python\Python310\site-packages\past\builtins\__init__.py", line 43, in <module>
    from past.builtins.noniterators import (filter, map, range, reduce, zip)
  File "C:\Users\EdingtonJames\AppData\Roaming\Python\Python310\site-packages\past\builtins\noniterators.py", line 24, in <module>
    from past.types import basestring
  File "C:\Users\EdingtonJames\AppData\Roaming\Python\Python310\site-packages\past\types\__init__.py", line 25, in <module>
    from .oldstr import oldstr
  File "C:\Users\EdingtonJames\AppData\Roaming\Python\Python310\site-packages\past\types\oldstr.py", line 5, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)
```

This blocks the corresponding issue in every project that depends on the `past` module, such as https://github.com/Wiston999/python-rubik/issues/14

**Comment by JamesTheAwesomeDude** [comment]
Actually, sorry; it looks like this is invalid; the dependent had pinned an old, broken version of the library. :/
