### ISSUE TITLE
future-0.18.3 python37/39/312 install failed

### ISSUE THREAD

**Issue by xingyun86** [PythonCharmers/python-future#630]
future-0.18.3 python37/39/312 install failed

···
  Using cached http://mirrors.aliyun.com/pypi/packages/8f/2e/cf6accf7415237d6faeeebdc7832023c90e0282aa16fd3263db0eb4715ec/future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\yfpps\AppData\Local\Temp\pip-install-n7thd398\future_9de4fec0af234f9ca6302e0f1d7c0664\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
···

Resolution：

add code:
import sys
sys.path.append('')
in setup.py;

**Comment by smrrazavian** [comment]
I have a same issue here for 0.18.3 version.
my python version is 3.18.2.
